query Characters($filter: FilterCharacter) {
  characters(filter: $filter) {
    results {
      id
      image
      name
      species
      status
      type
      gender
      origin {
        name
        type
        dimension
      }
      location {
        name
        type
        dimension
      }
    }
  }
}

