query Locations($filter: FilterLocation) {
  locations(filter: $filter) {
    results {
      name
      type
      dimension
      residents {
        name
      }
 
    }
  }
}

# {
#   "filter": {
#     "name": "Abadango",
#     "type": null,
#     "dimension": null
#   }
# }