query Episodes($filter: FilterEpisode) {
  episodes(filter: $filter) {
    results {
      episode
      name
      characters {
        name
      }
 
    }
  }
}

# {
#   "filter": {
#     "name": null,
#     "episode": "S05E01"
#   }
# }